import matplotlib.pyplot as plt
from pathlib import Path

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# =========================================================
# Alert report (Markdown + graph)
# =========================================================

def generate_alert(parcel_row):
    pid = parcel_row["parcel_id"]
    pname = parcel_row["parcel_name"]

    fig, ax = plt.subplots(figsize=(5, 3))
    ax.bar(
        ["Current", "7-day forecast"],
        [parcel_row["water_stress"], parcel_row["forecast_7d"]],
        color=["orange", "red"],
    )
    ax.set_ylabel("Water Stress Index")
    ax.set_title(f"Parcel {pid} — Stress Outlook")

    img_path = OUTPUT_DIR / f"parcel_{pid}_stress.png"
    plt.tight_layout()
    plt.savefig(img_path, dpi=200)
    plt.close()

    md = f"""# VITIS — Decision Support Alert

## Vineyard Parcel Assessment

**Parcel ID:** {pid}  
**Parcel Name:** {pname}

---

## 1. Vegetative Condition
- **Mean NDVI:** {parcel_row['mean_ndvi']:.3f}

---

## 2. Water Stress Assessment
- **Current Water Stress Index:** {parcel_row['water_stress']:.3f}
- **7-day Forecast Water Stress Index:** {parcel_row['forecast_7d']:.3f}
- **Stress Classification:** {parcel_row['stress_level']}

---

## 3. Decision Support Recommendation
**{parcel_row['recommendation']}**

---

## 4. Model Confidence
- **Decision confidence score:** {parcel_row['confidence']:.2f}

---

## 5. Stress Outlook Visualization
![Water stress forecast](parcel_{pid}_stress.png)

---

*Automatically generated by the VITIS Decision Support System.*
"""

    out_path = OUTPUT_DIR / f"parcel_{pid}_alert.md"
    out_path.write_text(md, encoding="utf-8")


# =========================================================
# Spatial risk map 
# =========================================================

def generate_spatial_risk_map(results_df, parcels_df):
    df = results_df.merge(
        parcels_df,
        left_on="parcel_id",
        right_on="id",
        how="left"
    )

    fig, ax = plt.subplots(figsize=(8, 6))

    scatter = ax.scatter(
        df["longitude"],
        df["latitude"],
        c=df["water_stress"],
        cmap="RdYlGn_r",
        s=120,
        edgecolor="black"
    )

    for _, row in df.iterrows():
        ax.text(
            row["longitude"],
            row["latitude"],
            str(int(row["parcel_id"])),
            fontsize=8,
            ha="center",
            va="center",
            color="black",
            weight="bold"
        )

    ax.set_title("VITIS — Spatial Water Stress Risk Map")
    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")

    cbar = plt.colorbar(scatter, ax=ax)
    cbar.set_label("Water Stress Index")

    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "vitis_risk_map.png", dpi=300)
    plt.close()